version: '3'

services:
  mongodb:
    build:
      context: ./MongoDB
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
    command: ["mongod", "--bind_ip_all"]

  scrapy:
    build:
      context: ./Scrapy
    depends_on:
      - mongodb

  application:
    build:
      context: ./Application
    ports:
      - "8050:8050"
    depends_on:
      - mongodb
      - scrapy
