# Utiliser l'image officielle MongoDB
FROM mongo:latest

LABEL authors="keren couton & matthieu constantin"

# Exposer le port par défaut de MongoDB
EXPOSE 27017

# Commande pour démarrer mongod avec bind_ip_all
CMD ["mongod", "--bind_ip_all"]
